### ISSUE TITLE
Color images

### ISSUE THREAD

**Issue by Alirezak2n** [riteshkumarumassedu/dncnn#1]
can somebody tell me what change should i make in code to accept color images(multichannel images) in test phase of code?

**Comment by riteshkumarumassedu** [comment]
AT line 88 in main_test.py you would need to convert the data 3 channel data to one channel data and respectively convert the final output from 1 channel output to 3 channel output. Hopefully, this should work. I have not tried this since the model is trained with only 1 channel data. However, you can give it a try.
